### ISSUE TITLE
Verbindung fehlgeschlagen

### ISSUE THREAD

**Issue by vagaone** [x789/xonox#8]
Hi,

evtl. kann mir ja jemand helfen.

Ich hab ein iRadio 300 und würde das hier gerne zum laufen bekommen. 

Was ich getan habe:

xonox server gestartet - OK
DNS Einträge umgebogen -OK
Aufrufe getestet (via DNS) - OK

Das Ding läuft also soweit.

Mein Problem ist jetzt aber, dass das Radio offensichtlich garnicht erst soweit kommt. Nach "klick" auf "Internet Radio" im Hauptmenü, versucht er sich ne Zeit lang zu verbinden, irgendwann kommt dann Netzwerkfehler.

Habe auch schon an der Fritzbox den Datenverkehr mitgetracked und mit Wireshark analysiert, aber zu dem Punkt, an dem er mal die entsprechenden Requests an den Server schicken würde, kommt er erst garnicht.

Der schickt irgendwelche TCP requests an die 0.0.0.0, die timen dann aus, ein paar Retries, und irgendwann kommt die Meldung und es passiert gar nichts mehr.

Hat evtl. irgendjemand einen Tip, was da evtl. falsch ist?

**Comment by x789** [comment]
Hi @vagaone,

IP-Pakete mit 0.0.0.0 werden beim DHCP-Discover verwendet. Haben die Pakete zufällig die MAC-Adresse des Radios als Absender? Werden die Pakete auf einer Schicht oberhalb von IP beantwortet? Falls du DHCP nutzt kann es sein, dass der DHCP-Service für das Radio nicht erreichbar ist.

Hast du mal probiert das Netzwerkinterface statisch zu konfigurieren?

Können xonox und das Radio in der Theorie Daten austauschen? Manche Router sind so konfiguriert, dass Daten z.B. nicht zwischen WiFi und Ethernet ausgetauscht werden dürfen...

**Comment by x789** [comment]
Falls du DHCP verwendest und das Radio auch eine IP bekommt: welcher DNS-Server wird per DHCP veröffentlicht? Ist es wirklich der, auf dem du die DNS-Einträge umgebogen hast?

**Comment by vagaone** [comment]
Hi, erstmal vielen Dank für den Input. 
Ich probier das mal aus / forsche nach und gebe wieder Feedback.

**Comment by vagaone** [comment]
Vielen Dank! Tatsächlich hatte die Fritzbox über DHCP einfach den falschen DNS ausgeliefert. Manuell im Gerät konfigurieren hat da dann geholfen.

Danke für die schnelle hilfe und ein schönes Wochenende noch :)
